simulation:
  time_scale: 120
  user_groups:
    - count: 1
      interactive: true
      rooms:
        - template: standard-room
          name_prefix: living-room
          type: reactive
          noisy: true
          count: 1
          devices:
            - template: climate-sensor
              name_prefix: climate-sensor
              count: 1
            - template: heater
              name_prefix: heater
              count: 1
            - template: humidifier
              name_prefix: humidifier
              count: 1
